import type { MapDef } from '../schema/map';
import { TEX, TILE } from '../textureKeys';

/**
 * 2002년 용곡중학교 — 중곡동 북쪽. 교사(校舍)는 막혀 있고 운동장에 W.I.T.O 병사들이 진을 쳤다.
 * 김훈 소대장 Q2(위토군 배치문서)의 무대.
 */
const W = 70;
const H = 52;
const FIELD = { x: 9, y: 19, w: 52, h: 24 }; // running track outer rect

export const yonggokMiddleSchool: MapDef = {
  id: 'yonggok-middle-school',
  name: '용곡중학교',
  year: 2002,
  width: W,
  height: H,
  tileSize: 32,
  groundTile: TILE.sidewalk,
  borderTile: TILE.concreteWall,
  fills: [
    // school forecourt paving
    { rect: { x: 1, y: 14, w: W - 2, h: 4 }, tile: TILE.schoolFloor },
    // track ring + infield grass with lane line
    { rect: FIELD, tile: TILE.track },
    { rect: { x: FIELD.x, y: FIELD.y + 1, w: FIELD.w, h: 1 }, tile: TILE.trackLine },
    { rect: { x: FIELD.x, y: FIELD.y + FIELD.h - 2, w: FIELD.w, h: 1 }, tile: TILE.trackLine },
    { rect: { x: FIELD.x + 3, y: FIELD.y + 3, w: FIELD.w - 6, h: FIELD.h - 6 }, tile: TILE.grass },
    // dirt patches around the goals
    { rect: { x: FIELD.x + 4, y: FIELD.y + 9, w: 5, h: 6 }, tile: TILE.dirt },
    { rect: { x: FIELD.x + FIELD.w - 9, y: FIELD.y + 9, w: 5, h: 6 }, tile: TILE.dirt },
    // road to the south gate
    { rect: { x: 31, y: 44, w: 8, h: 7 }, tile: TILE.asphalt },
    { rect: { x: 34, y: 45, w: 1, h: 5 }, tile: TILE.roadLine },
  ],
  obstacles: [
    // main school building (3 wings) — facade auto-generated by decorateTiles
    { rect: { x: 6, y: 3, w: 58, h: 10 }, tile: TILE.buildingRoof, kind: 'building' },
    { rect: { x: 2, y: 5, w: 4, h: 8 }, tile: TILE.buildingRoof, kind: 'building' },
    { rect: { x: 64, y: 5, w: 4, h: 8 }, tile: TILE.buildingRoof, kind: 'building' },
    // perimeter fence with gaps at the gate and along the forecourt
    { rect: { x: 1, y: 18, w: 7, h: 1 }, tile: TILE.fence, kind: 'fence' },
    { rect: { x: 62, y: 18, w: 7, h: 1 }, tile: TILE.fence, kind: 'fence' },
    { rect: { x: 1, y: 44, w: 30, h: 1 }, tile: TILE.fence, kind: 'fence' },
    { rect: { x: 39, y: 44, w: 30, h: 1 }, tile: TILE.fence, kind: 'fence' },
    // WITO field camp: sandbag walls (concrete stand-in) + parked truck (car tiles)
    { rect: { x: 26, y: 26, w: 4, h: 1 }, tile: TILE.concreteWall, kind: 'wall' },
    { rect: { x: 40, y: 34, w: 4, h: 1 }, tile: TILE.concreteWall, kind: 'wall' },
    { rect: { x: 33, y: 30, w: 2, h: 1 }, tile: TILE.car, kind: 'car' },
    { rect: { x: 36, y: 31, w: 2, h: 1 }, tile: TILE.car, kind: 'car' },
    { rect: { x: 12, y: 46, w: 2, h: 1 }, tile: TILE.car, kind: 'car' },
    { rect: { x: 55, y: 47, w: 2, h: 1 }, tile: TILE.car, kind: 'car' },
  ],
  decor: [
    { at: { x: 35, y: 17 }, tex: TEX.deco_flagpole, solid: true },
    { at: { x: 11, y: 30 }, tex: TEX.deco_goal, solid: true },
    { at: { x: 58, y: 30 }, tex: TEX.deco_goal, solid: true },
    ...[4, 16, 28, 41, 53, 65].map((x) => ({ at: { x, y: 46 }, tex: TEX.deco_tree, solid: true })),
    ...[2, 67].flatMap((x) => [22, 30, 38].map((y) => ({ at: { x, y }, tex: TEX.deco_tree, solid: true }))),
    { at: { x: 8, y: 16 }, tex: TEX.deco_bench, solid: true },
    { at: { x: 60, y: 16 }, tex: TEX.deco_bench, solid: true },
    { at: { x: 20, y: 16 }, tex: TEX.deco_vending, solid: true, interact: 'vending' },
    { at: { x: 22, y: 16 }, tex: TEX.deco_trash, solid: true },
    { at: { x: 47, y: 16 }, tex: TEX.deco_sign },
    { at: { x: 30, y: 49 }, tex: TEX.deco_lamp, solid: true },
    { at: { x: 39, y: 49 }, tex: TEX.deco_lamp, solid: true },
  ],
  spawnZones: [
    {
      id: 'field_camp',
      rect: { x: 12, y: 21, w: 46, h: 20 },
      monsters: [
        { id: 'wito_soldier', weight: 6 },
        { id: 'wito_recon', weight: 1 },
      ],
      maxAlive: 7,
      respawnSec: 20,
    },
    {
      id: 'forecourt',
      rect: { x: 2, y: 14, w: 66, h: 4 },
      monsters: [
        { id: 'zombie_suit_m', weight: 3 },
        { id: 'zombie_casual_f', weight: 2 },
      ],
      maxAlive: 4,
      respawnSec: 22,
    },
    {
      id: 'south_road',
      rect: { x: 2, y: 45, w: 66, h: 5 },
      monsters: [
        { id: 'zombie_stripe', weight: 2 },
        { id: 'zombie_casual_f', weight: 3 },
      ],
      maxAlive: 4,
      respawnSec: 20,
    },
  ],
  portals: [{ id: 'toJunggok', rect: { x: 33, y: 49, w: 4, h: 2 }, toMap: 'junggok-dong', toSpawn: 'fromSchool', label: '중곡동 거리로' }],
  spawnPoints: {
    default: { x: 35, y: 47 },
    fromJunggok: { x: 35, y: 47 },
    taxi: { x: 28, y: 15 },
  },
  npcs: [{ id: 'npc_taxi', at: { x: 26, y: 15 } }],
  safeZone: false,
};
