import { ANIM, TEX, type AnimKey, type TexKey } from '@data/textureKeys';
import { drawTilesAtlas, TILE_COUNT } from './draw/tiles';
import { FIGURE_STYLES, figureDrawer, drawPortrait, type FigureKey } from './draw/figures';
import { WALK_FRAMES } from '../systems/facing';
import {
  drawBarricade,
  drawRootNode,
  drawBooth,
  drawCasing,
  drawGate,
  drawIconAmmoIncendiary,
  drawIconAmmoNormal,
  drawIconArmorBottom,
  drawIconArmorTop,
  drawIconArmorCoat,
  drawIconArmorShoes,
  drawIconArmorHat,
  drawIconArmorWig,
  drawIconSkillActive,
  drawIconHpPack,
  drawIconSyringe,
  drawIconLens,
  drawIconAmpoule,
  drawIconTicket,
  drawIconCoupon,
  drawIconClaws,
  drawIconTentacle,
  drawIconAcid,
  drawIconBone,
  drawIconBandage,
  drawIconConsumable,
  drawIconDocument,
  drawIconPainkiller,
  drawIconEnergyDrink,
  drawIconGlock17,
  drawIconM1911,
  drawIconMp5,
  drawIconPistol,
  drawIconSkillMastery,
  drawIconSkillPassive,
  drawIconSmg,
  drawIconUzi,
  drawIconM16,
  drawIconAk47,
  drawIconShotgun,
  drawIconSniper,
  drawIconMg,
  drawIconBaton,
  drawIconMachete,
  drawIconAxe,
  drawIconLauncher,
  drawIconAmmoAp,
  drawIconAmmoShell,
  drawIconAmmoSlug,
  drawIconAmmoGrenade,
  drawIconAmmoRocket,
  drawPickupItem,
  drawPickupWon,
} from './draw/items';
import { drawTitleBackground } from './draw/title';
import { drawBlood, drawExplosion, drawFire, drawJumpMarker, drawMuzzle, drawRocket, drawScorch, drawShellGrenade, drawSmokePuff, drawTracer } from './draw/fx';
import { drawBench, drawBusStop, drawFlagpole, drawGoal, drawHydrant, drawLamp, drawPhone, drawPillar, drawSign, drawTrash, drawTree, drawVending } from './draw/decor';
import { drawCrosshair, drawUiPanel, drawUiSlot } from './draw/ui';

export type DrawFn = (ctx: CanvasRenderingContext2D, frame: number, w: number, h: number) => void;

export interface TextureSpec {
  frameW: number;
  frameH: number;
  frames: number;
  /** frame layout; omitted = one horizontal strip */
  grid?: { cols: number; rows: number };
  draw: DrawFn;
  anim?: { key: AnimKey; frameRate: number; repeat: number };
}

/** 8 directions × 4 walk frames, row per direction. */
const figure = (key: FigureKey, size = 48): TextureSpec => ({
  frameW: size,
  frameH: size,
  frames: 8 * WALK_FRAMES,
  grid: { cols: WALK_FRAMES, rows: 8 },
  draw: figureDrawer(FIGURE_STYLES[key]),
});

const single = (draw: DrawFn, w: number, h = w): TextureSpec => ({ frameW: w, frameH: h, frames: 1, draw });

/**
 * Every texture the game uses. Swapping a procedural entry for real art later means replacing
 * its `draw` with a spritesheet load — no game code references how a key was produced.
 */
export const TEXTURE_MANIFEST: Record<TexKey, TextureSpec> = {
  [TEX.tiles]: { frameW: 32 * TILE_COUNT, frameH: 32, frames: 1, draw: (ctx) => drawTilesAtlas(ctx) },

  [TEX.player]: figure('player'),
  [TEX.player_infected]: figure('player_infected'),
  [TEX.player_smg]: figure('player_smg'),
  [TEX.player_rifle]: figure('player_rifle'),
  [TEX.player_melee]: figure('player_melee'),
  [TEX.portrait_player]: single((ctx, _f, w, h) => drawPortrait(ctx, FIGURE_STYLES.player, w, h), 64),
  [TEX.portrait_infected]: single((ctx, _f, w, h) => drawPortrait(ctx, FIGURE_STYLES.player_infected, w, h), 64),
  // dialog faces — procedural fallbacks; `TextureGenScene` loads real art over these keys when available
  [TEX.face_elia]: single((ctx, _f, w, h) => drawPortrait(ctx, FIGURE_STYLES.npc_elia, w, h), 64),
  [TEX.face_shop]: single((ctx, _f, w, h) => drawPortrait(ctx, FIGURE_STYLES.npc_shop, w, h), 64),
  [TEX.face_tech]: single((ctx, _f, w, h) => drawPortrait(ctx, FIGURE_STYLES.npc_tech, w, h), 64),
  [TEX.face_blackmarket]: single((ctx, _f, w, h) => drawPortrait(ctx, FIGURE_STYLES.npc_blackmarket, w, h), 64),
  [TEX.face_mainstream]: single((ctx, _f, w, h) => drawPortrait(ctx, FIGURE_STYLES.npc_mainstream, w, h), 64),
  [TEX.face_storage]: single((ctx, _f, w, h) => drawPortrait(ctx, FIGURE_STYLES.npc_storage, w, h), 64),
  [TEX.face_parallel]: single((ctx, _f, w, h) => drawPortrait(ctx, FIGURE_STYLES.npc_parallel, w, h), 64),
  [TEX.face_kimhun]: single((ctx, _f, w, h) => drawPortrait(ctx, FIGURE_STYLES.npc_kimhun, w, h), 64),
  [TEX.face_trainer]: single((ctx, _f, w, h) => drawPortrait(ctx, FIGURE_STYLES.npc_assault, w, h), 64),
  [TEX.face_taxi]: single((ctx, _f, w, h) => drawPortrait(ctx, FIGURE_STYLES.npc_taxi, w, h), 64),
  [TEX.face_assault]: single((ctx, _f, w, h) => drawPortrait(ctx, FIGURE_STYLES.npc_assault, w, h), 64),

  [TEX.zombie_casual_f]: figure('zombie_casual_f'),
  [TEX.zombie_suit_m]: figure('zombie_suit_m'),
  [TEX.zombie_stripe]: figure('zombie_stripe'),
  [TEX.zombie_banshee]: figure('zombie_banshee'),
  [TEX.zombie_lord]: figure('zombie_lord', 64),
  [TEX.zombie_dog]: figure('zombie_dog'),
  [TEX.zombie_hardened]: figure('zombie_hardened', 56),
  [TEX.zombie_worker]: figure('zombie_worker'),
  [TEX.ogurin]: figure('ogurin', 64),
  [TEX.ogurin_mutant]: figure('ogurin_mutant'),
  [TEX.zombie_police]: figure('zombie_police'),
  [TEX.zombie_firefighter]: figure('zombie_firefighter'),
  [TEX.wito_engineer]: figure('wito_engineer'),
  [TEX.wito_turret]: figure('wito_turret'),
  [TEX.zombie_fire_chief]: figure('zombie_fire_chief', 64),
  [TEX.npc_parallel]: figure('npc_parallel'),
  [TEX.zombie_soldier]: figure('zombie_soldier'),
  [TEX.larva]: figure('larva'),
  [TEX.wito_elite_trooper]: figure('wito_elite_trooper'),
  [TEX.mongolian_deathworm]: figure('mongolian_deathworm', 96),
  [TEX.guest_scout]: figure('guest_scout'),
  [TEX.guest_warrior]: figure('guest_warrior'),
  [TEX.parasite_root]: figure('parasite_root', 96),
  [TEX.root_node]: single(drawRootNode, 64),
  [TEX.zombie_office]: figure('zombie_office'),
  [TEX.wito_heavy_gunner]: figure('wito_heavy_gunner'),
  [TEX.guest_hunter]: figure('guest_hunter'),
  [TEX.zombie_ceo]: figure('zombie_ceo', 64),
  [TEX.zombie_riot_police]: figure('zombie_riot_police'),
  [TEX.wito_drone]: figure('wito_drone'),
  [TEX.parasite_spawn]: figure('parasite_spawn'),
  [TEX.wito_commander]: figure('wito_commander', 64),
  [TEX.zombie_ancient]: figure('zombie_ancient'),
  [TEX.guest_elite]: figure('guest_elite'),
  [TEX.parasite_horror]: figure('parasite_horror', 64),
  [TEX.the_wise_one]: figure('the_wise_one', 128),

  [TEX.wito_recon]: figure('wito_recon'),
  [TEX.wito_airborne]: figure('wito_airborne'),
  [TEX.wito_elite]: figure('wito_elite'),

  [TEX.npc_elia]: figure('npc_elia'),
  [TEX.npc_shop]: figure('npc_shop'),
  [TEX.npc_assault]: figure('npc_assault'),
  [TEX.npc_kimhun]: figure('npc_kimhun'),
  [TEX.npc_taxi]: figure('npc_taxi'),
  [TEX.npc_tech]: figure('npc_tech'),
  [TEX.npc_blackmarket]: figure('npc_blackmarket'),
  [TEX.npc_mainstream]: figure('npc_mainstream'),
  [TEX.npc_storage]: figure('npc_storage'),
  [TEX.wito_soldier]: figure('wito_soldier'),

  [TEX.deco_lamp]: single(drawLamp, 32, 80),
  [TEX.deco_vending]: single(drawVending, 32, 56),
  [TEX.deco_trash]: single(drawTrash, 24, 32),
  [TEX.deco_phone]: single(drawPhone, 32, 64),
  [TEX.deco_sign]: single(drawSign, 24, 56),
  [TEX.deco_tree]: single(drawTree, 64, 80),
  [TEX.deco_hydrant]: single(drawHydrant, 16, 28),
  [TEX.deco_bench]: single(drawBench, 48, 24),
  [TEX.deco_busstop]: single(drawBusStop, 64, 72),
  [TEX.deco_pillar]: single(drawPillar, 32, 72),
  [TEX.deco_goal]: single(drawGoal, 64, 40),
  [TEX.deco_flagpole]: single(drawFlagpole, 24, 96),

  [TEX.barricade]: single(drawBarricade, 64),
  [TEX.gate]: single(drawGate, 32),
  [TEX.booth]: { frameW: 64, frameH: 64, frames: 3, draw: drawBooth },
  [TEX.pickup_won]: single(drawPickupWon, 16),
  [TEX.pickup_item]: single(drawPickupItem, 16),

  [TEX.tracer]: single(drawTracer, 16, 4),
  [TEX.muzzle]: single(drawMuzzle, 16),
  [TEX.blood]: single(drawBlood, 24),
  [TEX.fire]: { frameW: 16, frameH: 16, frames: 3, draw: drawFire, anim: { key: ANIM.fire_burn, frameRate: 10, repeat: -1 } },
  [TEX.jump_marker]: single(drawJumpMarker, 80),
  [TEX.shell_grenade]: single(drawShellGrenade, 10, 6),
  [TEX.rocket]: single(drawRocket, 22, 8),
  [TEX.explosion]: { frameW: 96, frameH: 96, frames: 6, draw: drawExplosion, anim: { key: ANIM.explosion_blast, frameRate: 18, repeat: 0 } },
  [TEX.scorch]: single(drawScorch, 64),
  [TEX.smoke_puff]: single(drawSmokePuff, 16),

  [TEX.ui_panel]: single(drawUiPanel, 48),
  [TEX.ui_slot]: single(drawUiSlot, 48),
  [TEX.crosshair]: single(drawCrosshair, 24),

  [TEX.casing]: single(drawCasing, 5, 3),
  [TEX.title_bg]: single(drawTitleBackground, 1280, 720),

  [TEX.icon_pistol]: single(drawIconPistol, 32),
  [TEX.icon_smg]: single(drawIconSmg, 32),
  [TEX.icon_glock17]: single(drawIconGlock17, 32),
  [TEX.icon_m1911]: single(drawIconM1911, 32),
  [TEX.icon_mp5]: single(drawIconMp5, 32),
  [TEX.icon_uzi]: single(drawIconUzi, 32),
  [TEX.icon_m16]: single(drawIconM16, 32),
  [TEX.icon_ak47]: single(drawIconAk47, 32),
  [TEX.icon_shotgun]: single(drawIconShotgun, 32),
  [TEX.icon_sniper]: single(drawIconSniper, 32),
  [TEX.icon_mg]: single(drawIconMg, 32),
  [TEX.icon_baton]: single(drawIconBaton, 32),
  [TEX.icon_machete]: single(drawIconMachete, 32),
  [TEX.icon_axe]: single(drawIconAxe, 32),
  [TEX.icon_launcher]: single(drawIconLauncher, 32),
  [TEX.icon_ammo_ap]: single(drawIconAmmoAp, 32),
  [TEX.icon_ammo_shell]: single(drawIconAmmoShell, 32),
  [TEX.icon_ammo_slug]: single(drawIconAmmoSlug, 32),
  [TEX.icon_ammo_grenade]: single(drawIconAmmoGrenade, 32),
  [TEX.icon_ammo_rocket]: single(drawIconAmmoRocket, 32),
  [TEX.icon_bandage]: single(drawIconBandage, 32),
  [TEX.icon_energy_drink]: single(drawIconEnergyDrink, 32),
  [TEX.icon_document]: single(drawIconDocument, 32),
  [TEX.icon_painkiller]: single(drawIconPainkiller, 32),
  [TEX.icon_ammo_normal]: single(drawIconAmmoNormal, 32),
  [TEX.icon_ammo_incendiary]: single(drawIconAmmoIncendiary, 32),
  [TEX.icon_armor_top]: single(drawIconArmorTop, 32),
  [TEX.icon_armor_bottom]: single(drawIconArmorBottom, 32),
  [TEX.icon_armor_coat]: single(drawIconArmorCoat, 32),
  [TEX.icon_armor_shoes]: single(drawIconArmorShoes, 32),
  [TEX.icon_armor_hat]: single(drawIconArmorHat, 32),
  [TEX.icon_armor_wig]: single(drawIconArmorWig, 32),
  [TEX.icon_skill_active]: single(drawIconSkillActive, 32),
  [TEX.icon_hp_pack]: single(drawIconHpPack, 32),
  [TEX.icon_syringe]: single(drawIconSyringe, 32),
  [TEX.icon_lens]: single(drawIconLens, 32),
  [TEX.icon_ampoule]: single(drawIconAmpoule, 32),
  [TEX.icon_ticket]: single(drawIconTicket, 32),
  [TEX.icon_coupon]: single(drawIconCoupon, 32),
  [TEX.icon_claws]: single(drawIconClaws, 32),
  [TEX.icon_tentacle]: single(drawIconTentacle, 32),
  [TEX.icon_acid]: single(drawIconAcid, 32),
  [TEX.icon_bone]: single(drawIconBone, 32),
  [TEX.npc_cyber]: figure('npc_cyber'),
  [TEX.icon_skill_passive]: single(drawIconSkillPassive, 32),
  [TEX.icon_skill_mastery]: single(drawIconSkillMastery, 32),
  [TEX.icon_consumable]: single(drawIconConsumable, 32),
};
